POST http://localhost:3000/api/cadastro
Content-Type: application/json

{
    "name": "Alan",
    "email": "alan@empresarial.com",
    "password": "teste",
    "confirmpassword": "teste",
    "budget": 4750,
    "image": "https://images.pexels.com/photos/244206/pexels-photo-244206.jpeg"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "name": "Alan",
    "email": "alan@empresarial.com",
    "password": "teste"
}
###

GET  http://localhost:3000/api/user/$2b$12$zfGZ4VhiPk8k5aRACYh2G.XQh.qgesXEjmRhDrfDEYAWsxyeRzgo.
Content-Type: application/json


###
POST  http://localhost:3000/api/service
Content-Type: application/json

{
    "name": "Adição de central multimídia",
    "description": "adicione uma central multimidia no seu carro.",
    "price": 1500,
    "image": "https://images.pexels.com/photos/13535542/pexels-photo-13535542.jpeg"
}

###
GET  http://localhost:3000/api/service

###
GET http://localhost:3000/api/service/$2b$12$RyjCXdvIqzMeQp7WJYdqduBbCiNGmYv7jx7fvcgX5/MVbv4l2Or/e

###
PUT http://localhost:3000/api/service/6880e3635a8292fc012a9c4d
Content-Type: application/json

{
    "name": "Vistoria veicular",
    "description": "Para fazer a checagem completa para o seu carro.",
    "price": 240,
    "image": "https://contagemmotorpecas.com.br/wp-content/uploads/2024/02/vistoria-veicular.jpg"
}

### 
PUT http://localhost:3000/api/user/addServices/6882735429e35f288d88ce94
Content-Type: application/json

{
    "services": [
                {
                    "name": "Lavagem",
                    "description": "Lavagem completa para o seu carro.",
                    "price": 350,
                    "image": "https://images.pexels.com/photos/372810/pexels-photo-372810.jpeg"
                },
                {
                    "name": "Vistoria veicular",
                    "description": "Para fazer a checagem completa para o seu carro.",
                    "price": 240,
                    "image": "https://contagemmotorpecas.com.br/wp-content/uploads/2024/02/vistoria-veicular.jpg"
                }
                ]
}

###

DELETE http://localhost:3000/api/user/deleteUserServices/6882735429e35f288d88ce94
Content-Type: application/json

{
    "serviceId": "6880d8d4a215a6a738b0221c"
}