### Buscar transações do usuário autenticado
GET http://localhost:3000/transactions
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJiN2JhZmIyZjEwY2FlMmIxZjA3ZjM4MTZjNTQyMmJlY2NhNWMyMjMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29udHJvbGUtZGUtZ2FzdG9zLTYxNTY3IiwiYXVkIjoiY29udHJvbGUtZGUtZ2FzdG9zLTYxNTY3IiwiYXV0aF90aW1lIjoxNzU0ODY3Mzc5LCJ1c2VyX2lkIjoiQmpzb291c3lYNVY4d0l3TGtrWHFpT2JHamV5MSIsInN1YiI6IkJqc29vdXN5WDVWOHdJd0xra1hxaU9iR2pleTEiLCJpYXQiOjE3NTQ4NjczNzksImV4cCI6MTc1NDg3MDk3OSwiZW1haWwiOiJqb3NpYXNAaG90bWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiam9zaWFzQGhvdG1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.vJ-14Ovm3cPbDgIQQ8b1GOG-i3qFpBVFKcq_8DC2RlgGV_7Op-4w8qRwz0ZyD8nz48VXtzNUSFhGF8YBFzPoAJmqtdWVBDOvjCby2S9cG7DRfRhjCd2EAfkAojEb2CiVIR7_ubMsVi9QQ4wMMEGBgKxcVll3h0eFg2YMrHONkquIAxMnYj9lR8aRlUQFhdu_6S0KLSXJi9_RV2TCM3__K28vS1xUgLz6X6hGzJlnf4AzGSfc3cCkHTtKjRtjk99WaFCR1syopsLxgSskQkftM-Y3agT4o6nZat2pj-eWh1sDtZusMxL5iibMnCYcqgiPMGwBR6SNn11svnqUKG_-dA